#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LIB_DIR="${1:-$ROOT_DIR/dist/lib}"
CONFIG_FILE="$ROOT_DIR/Config/MLCRuntime.xcconfig"

"$ROOT_DIR/scripts/verify-mlc-runtime-artifacts.sh" "$LIB_DIR" "$ROOT_DIR/dist/bundle"

cat > "$CONFIG_FILE" <<'EOF'
// Generated by scripts/enable-mlc-runtime-link.sh.
// Do not hand-edit after packaging; regenerate from dist/lib.

BEMORE_MLC_RUNTIME_LINKED = 1
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) BEMORE_MLC_RUNTIME_LINKED=1 TVM_USE_LIBBACKTRACE=0
LIBRARY_SEARCH_PATHS = $(inherited) "$(SRCROOT)/dist/lib"
OTHER_LDFLAGS = $(inherited) -Wl,-all_load -lmodel_iphone -lmlc_llm -ltvm_runtime -ltokenizers_cpp -lsentencepiece -ltokenizers_c -lc++ -lz
EOF

echo "Enabled native MLC runtime link in $CONFIG_FILE"
