const canvas=document.querySelector('#game');
const ctx=canvas.getContext('2d');
const logEl=document.querySelector('#log');
const W=canvas.width,H=canvas.height,keys=new Set(),pressed=new Set();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const hyp=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const ang=(a,b)=>Math.atan2(b.y-a.y,b.x-a.x);
const rnd=()=>Math.random().toString(16).slice(2);
const log=t=>{const li=document.createElement('li');li.textContent=t;logEl.prepend(li);while(logEl.children.length>12)logEl.lastChild.remove()};
function once(c){if(pressed.has(c)){pressed.delete(c);return true}return false}
addEventListener('keydown',e=>{if(['Space','Tab','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(!keys.has(e.code))pressed.add(e.code);keys.add(e.code)});
addEventListener('keyup',e=>keys.delete(e.code));
class E{constructor(o){Object.assign(this,{id:rnd(),x:0,y:0,r:14,hp:100,max:100,color:'#fff',team:'neutral',alive:true,shield:0,ifr:0,status:new Map()},o)}
 get pct(){return this.hp/this.max}
 hit(n,src='hit'){if(!this.alive||this.ifr>0)return false;let block=Math.min(this.shield,n);this.shield-=block;n=Math.max(0,n-block);this.hp=clamp(this.hp-n,0,this.max);if(n>0)float.push({t:`-${Math.round(n)}`,x:this.x,y:this.y-20,c:'#ff9a9a',life:.75});if(block>0)float.push({t:`block ${Math.round(block)}`,x:this.x,y:this.y-36,c:'#b5d8ff',life:.75});if(this.hp<=0){this.alive=false;log(`${this.name} was knocked out by ${src}.`)}return n>0}
 heal(n){if(!this.alive)return;let b=this.hp;this.hp=clamp(this.hp+n,0,this.max);let g=this.hp-b;if(g>0)float.push({t:`+${Math.round(g)}`,x:this.x,y:this.y-20,c:'#9cffb7',life:.75})}
 tick(dt){this.ifr=Math.max(0,this.ifr-dt);for(const [k,s]of[...this.status]){s.t-=dt;if(s.t<=0)this.status.delete(k)}}}
class Trainer extends E{constructor(){super({name:'Trainer',x:210,y:320,r:13,max:120,hp:120,color:'#f6d365',team:'player'});this.speed=205;this.face=0;this.dodge=0}
 tick(dt){super.tick(dt);this.dodge=Math.max(0,this.dodge-dt);let x=0,y=0;if(keys.has('KeyW')||keys.has('ArrowUp'))y--;if(keys.has('KeyS')||keys.has('ArrowDown'))y++;if(keys.has('KeyA')||keys.has('ArrowLeft'))x--;if(keys.has('KeyD')||keys.has('ArrowRight'))x++;let m=Math.hypot(x,y)||1;x/=m;y/=m;if(x||y)this.face=Math.atan2(y,x);if(once('Space')&&this.dodge<=0){this.dodge=.85;this.ifr=.22;this.x+=Math.cos(this.face)*42;this.y+=Math.sin(this.face)*42;float.push({t:'dodge',x:this.x,y:this.y-28,c:'#fff',life:.55})}this.x=clamp(this.x+x*this.speed*dt,34,W-34);this.y=clamp(this.y+y*this.speed*dt,74,H-46)}}
class Creature extends E{constructor(def,x,y,team){super({name:def.name,x,y,r:def.r,max:def.max,hp:def.max,color:def.color,team});this.def=def;this.cool={};this.cast=null;this.speed=def.speed;this.power=def.power||1;this.ai=0}
 can(){return !this.cast||this.cast.phase==='recovery'}
 use(i,target){let m=this.def.moves[i];if(!this.alive||!m||this.cool[m.id]>0||this.cast&&this.cast.phase!=='recovery')return false;this.cast={m,phase:'windup',t:m.wind,dir:ang(this,target),target};this.cool[m.id]=m.cd;log(`${this.name} started ${m.name}.`);return true}
 tick(dt){super.tick(dt);for(const k of Object.keys(this.cool))this.cool[k]=Math.max(0,this.cool[k]-dt);if(!this.cast)return;let s=this.cast;s.t-=dt;if(s.phase==='windup'&&s.t<=0){s.phase='active';s.t=s.m.active;apply(this,s)}else if(s.phase==='active'&&s.t<=0){s.phase='recovery';s.t=s.m.rec}else if(s.phase==='recovery'&&s.t<=0)this.cast=null}}
const defs={
 sprout:{name:'Sproutbit',max:145,r:15,speed:150,power:1,color:'#82d173',role:'Control',moves:[mv('leaf','Leaf Jab','line',18,92,28,.18,.08,.22,1.15,'#9cff95'),mv('snare','Vine Snare','circle',10,170,48,.48,.1,.32,5,'#7bd36f',{name:'root',t:1.2}),mv('guard','Verdant Guard','shield',0,0,0,.1,.05,.15,7,'#c5ffbf'),mv('seed','Seed Burst','nova',22,0,76,.62,.1,.45,6,'#d4ff85')]},
 ember:{name:'Embermite',max:115,r:14,speed:180,power:1.08,color:'#ff8b54',role:'Burst',moves:[mv('cone','Flame Cone','cone',22,105,.78,.22,.12,.28,1.55,'#ff9f5f'),mv('dash','Cinder Dash','dash',24,118,34,.18,.1,.42,4.2,'#ff6b35'),mv('ash','Ash Trap','circle',12,155,42,.35,.1,.28,4.8,'#ffb36a',{name:'burn',t:2}),mv('heat','Overheat','nova',36,0,82,.78,.12,.85,9,'#ff4d4d')]},
 tide:{name:'Tidepup',max:130,r:15,speed:165,power:1,color:'#74c7ec',role:'Support',moves:[mv('shot','Aqua Shot','line',18,260,18,.2,.1,.22,1.25,'#8be3ff'),mv('bubble','Bubble Guard','shield',0,0,0,.1,.05,.15,5.2,'#b7f3ff'),mv('rush','Tide Rush','dash',18,92,46,.2,.1,.32,3.5,'#53d8ff'),mv('rain','Healing Rain','heal',0,0,92,.52,.1,.42,9.5,'#b9f9ff')]},
 wild:{name:'Wild Bramblehorn',max:220,r:20,speed:122,power:1,color:'#d9a441',role:'Wild',moves:[mv('horn','Horn Line','line',20,115,34,.42,.12,.38,2.6,'#ffd166'),mv('stamp','Stampede','dash',26,142,42,.58,.18,.55,5.2,'#f7b538'),mv('bloom','Ground Bloom','circle',22,140,56,.8,.16,.32,6.4,'#d4a373')]},
 alpha:{name:'Alpha Bramblehorn',max:820,r:34,speed:108,power:1.35,color:'#e85d75',role:'Alpha',moves:[mv('charge','Alpha Charge','dash',42,210,70,.75,.22,.65,5.6,'#ff758f'),mv('quake','Thorn Quake','nova',34,0,135,1.1,.16,.65,7.8,'#ffb703'),mv('prison','Root Prison','circle',26,195,72,.9,.12,.45,8.8,'#90be6d',{name:'root',t:1.1}),mv('roar','Alpha Roar','cone',28,190,1.1,.6,.12,.38,6.5,'#ffcad4')]}}
function mv(id,name,type,dmg,range,size,wind,active,rec,cd,color,status){return{id,name,type,dmg,range,size,wind,active,rec,cd,color,status}}
let trainer,party,active,enemy,boxes,teles,float,alpha,score,paused=false;
function reset(a=false){trainer=new Trainer();party=[new Creature(defs.sprout,250,330,'player'),new Creature(defs.ember,250,370,'player'),new Creature(defs.tide,250,290,'player')];active=0;enemy=new Creature(a?defs.alpha:defs.wild,690,320,'enemy');boxes=[];teles=[];float=[];alpha=a;score={dmg:0,cap:0};paused=false;log(a?'Alpha mode started.':'Wild battle started. Weaken Bramblehorn and press C.')}
function cur(){return party[active]}
function shape(user,s){let m=s.m,d=s.dir;if(['line','dash'].includes(m.type))return{type:'line',x:user.x,y:user.y,dir:d,len:m.range,w:m.size,c:m.color};if(m.type==='cone')return{type:'cone',x:user.x,y:user.y,dir:d,len:m.range,a:m.size,c:m.color};if(['circle'].includes(m.type)){let t=s.target;return{type:'circle',x:clamp(t.x,50,W-50),y:clamp(t.y,90,H-50),r:m.size,c:m.color}}return{type:'circle',x:user.x,y:user.y,r:m.size,c:m.color}}
function apply(user,s){let m=s.m;if(m.type==='shield'){user.shield+=m.id==='bubble'?28:36;float.push({t:'shield',x:user.x,y:user.y-32,c:m.color,life:.7});return}if(m.type==='heal'){for(const p of party)if(p.alive&&hyp(user,p)<m.size)p.heal(24);user.heal(34);teles.push({...shape(user,s),life:.25});return}if(m.type==='dash'){user.x=clamp(user.x+Math.cos(s.dir)*m.range,34,W-34);user.y=clamp(user.y+Math.sin(s.dir)*m.range,74,H-46)}let sh=shape(user,s);boxes.push({sh,user,team:user.team,d:m.dmg*user.power,st:m.status,src:m.name,life:Math.max(.08,m.active),seen:new Set()});teles.push({...sh,life:.18})}
function hits(sh,e){if(!e.alive)return false;if(sh.type==='circle')return Math.hypot(e.x-sh.x,e.y-sh.y)<=sh.r+e.r;if(sh.type==='line'){let ax=e.x-sh.x,ay=e.y-sh.y,al=ax*Math.cos(sh.dir)+ay*Math.sin(sh.dir),pe=Math.abs(-Math.sin(sh.dir)*ax+Math.cos(sh.dir)*ay);return al>=-e.r&&al<=sh.len+e.r&&pe<=sh.w/2+e.r}if(sh.type==='cone'){let d=Math.hypot(e.x-sh.x,e.y-sh.y);if(d>sh.len+e.r)return false;let da=Math.atan2(Math.sin(Math.atan2(e.y-sh.y,e.x-sh.x)-sh.dir),Math.cos(Math.atan2(e.y-sh.y,e.x-sh.x)-sh.dir));return Math.abs(da)<=sh.a/2}return false}
function tickBoxes(dt){for(const b of boxes){b.life-=dt;let targets=b.team==='player'?[enemy]:[trainer,...party];for(const t of targets){if(!t.alive||b.seen.has(t.id)||!hits(b.sh,t))continue;b.seen.add(t.id);if(t.hit(b.d,b.src)&&b.team==='player')score.dmg+=b.d;if(b.st)t.status.set(b.st.name,{...b.st})}}boxes=boxes.filter(b=>b.life>0);teles.forEach(t=>t.life-=dt);teles=teles.filter(t=>t.life>0)}
function swap(){for(let i=1;i<=party.length;i++){let n=(active+i)%party.length;if(party[n].alive){active=n;cur().x=trainer.x+38;cur().y=trainer.y+16;log(`Swapped to ${cur().name}.`);return}}}
function capture(){if(alpha){log('Alpha creatures use raid rewards, not direct capture.');return}if(!enemy.alive){log('Cannot capture a knocked out creature.');return}if(hyp(trainer,enemy)>105){log('Move closer before throwing.');return}let ch=clamp(.14+(1-enemy.pct)*.72+(enemy.status.size?.08:0),.06,.88);if(Math.random()<ch){enemy.alive=false;score.cap++;log(`Captured ${enemy.name}! Chance ${Math.round(ch*100)}%.`)}else log(`Capture failed. Chance ${Math.round(ch*100)}%.`)}
function input(){if(once('KeyP'))paused=!paused;if(once('Enter'))reset(alpha);if(once('KeyR'))reset(!alpha);if(paused)return;if(once('Tab'))swap();if(once('KeyC'))capture();let c=cur();if(once('Digit1'))c.use(0,enemy);if(once('Digit2'))c.use(1,enemy);if(once('Digit3'))c.use(2,enemy);if(once('Digit4'))c.use(3,enemy)}
function ai(dt){if(!enemy.alive)return;enemy.ai-=dt;let c=cur().alive?cur():trainer,t=hyp(enemy,trainer)<hyp(enemy,c)?trainer:c,d=hyp(enemy,t);if(enemy.can()&&!enemy.status.has('root')){let want=alpha?170:120;if(d>want){let a=ang(enemy,t);enemy.x+=Math.cos(a)*enemy.speed*dt;enemy.y+=Math.sin(a)*enemy.speed*dt}else if(d<70){let a=ang(t,enemy);enemy.x+=Math.cos(a)*enemy.speed*.55*dt;enemy.y+=Math.sin(a)*enemy.speed*.55*dt}}if(enemy.ai<=0){let a=enemy.def.moves.map((m,i)=>({m,i})).filter(o=>!enemy.cool[o.m.id]);if(a.length){let p=a[Math.floor(Math.random()*a.length)];enemy.use(p.i,t);enemy.ai=alpha?1.4+Math.random():1.8+Math.random()*1.2}}}
function follow(dt){let c=cur();if(!c.alive)return;let ix=trainer.x+Math.cos(trainer.face+.7)*46,iy=trainer.y+Math.sin(trainer.face+.7)*46,d=Math.hypot(ix-c.x,iy-c.y);if(d>5&&c.can()&&!c.status.has('root')){c.x+=(ix-c.x)/d*c.speed*dt;c.y+=(iy-c.y)/d*c.speed*dt}}
function step(dt){input();if(paused)return;trainer.tick(dt);follow(dt);party.forEach(p=>p.tick(dt));enemy.tick(dt);ai(dt);tickBoxes(dt);if(enemy.alive&&hyp(enemy,trainer)<enemy.r+trainer.r+3)trainer.hit((alpha?12:7)*dt,'contact');float.forEach(f=>{f.life-=dt;f.y-=28*dt});float=float.filter(f=>f.life>0)}
function drawShape(s,a=.25,fill=true){ctx.save();ctx.globalAlpha=a;ctx.fillStyle=ctx.strokeStyle=s.c||'#fff';ctx.lineWidth=2;if(s.type==='circle'){ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);fill?ctx.fill():ctx.stroke()}if(s.type==='line'){ctx.translate(s.x,s.y);ctx.rotate(s.dir);fill?ctx.fillRect(0,-s.w/2,s.len,s.w):ctx.strokeRect(0,-s.w/2,s.len,s.w)}if(s.type==='cone'){ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.arc(s.x,s.y,s.len,s.dir-s.a/2,s.dir+s.a/2);ctx.closePath();fill?ctx.fill():ctx.stroke()}ctx.restore()}
function hp(e,x,y,w=68,h=7){ctx.fillStyle='rgba(0,0,0,.5)';ctx.fillRect(x,y,w,h);ctx.fillStyle=e.pct>.45?'#82d173':e.pct>.2?'#ffd166':'#ff6b6b';ctx.fillRect(x,y,w*clamp(e.pct,0,1),h);if(e.shield>0){ctx.fillStyle='#9bd8ff';ctx.fillRect(x,y+h+2,w*clamp(e.shield/70,0,1),3)}}
function ent(e,on=false){if(!e.alive)return;ctx.fillStyle='rgba(0,0,0,.28)';ctx.beginPath();ctx.ellipse(e.x,e.y+e.r*.7,e.r*1.1,e.r*.42,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=e.color;ctx.beginPath();ctx.arc(e.x,e.y,e.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111';ctx.fillRect(e.x+e.r*.22,e.y-e.r*.25,4,4);ctx.fillRect(e.x+e.r*.22,e.y+e.r*.16,4,4);if(on){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(e.x,e.y,e.r+5,0,Math.PI*2);ctx.stroke()}if(e.status.size){ctx.strokeStyle='#ffe66d';ctx.beginPath();ctx.arc(e.x,e.y,e.r+9,0,Math.PI*2);ctx.stroke()}hp(e,e.x-34,e.y-e.r-19)}
function render(){ctx.fillStyle='#233121';ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(255,255,255,.055)';for(let x=0;x<W;x+=32){ctx.beginPath();ctx.moveTo(x,64);ctx.lineTo(x,H);ctx.stroke()}for(let y=64;y<H;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.fillStyle='#182018';ctx.fillRect(0,0,W,64);teles.forEach(t=>drawShape(t,.25,true));boxes.forEach(b=>drawShape(b.sh,.12,true));for(const c of[cur(),enemy])if(c.cast&&c.cast.phase==='windup')drawShape(shape(c,c.cast),.22,false);ctx.strokeStyle='rgba(255,255,255,.14)';ctx.beginPath();ctx.moveTo(trainer.x,trainer.y);ctx.lineTo(cur().x,cur().y);ctx.stroke();ent(trainer);ent(cur(),true);ent(enemy);float.forEach(f=>{ctx.globalAlpha=clamp(f.life/.75,0,1);ctx.fillStyle=f.c;ctx.font='800 14px system-ui';ctx.fillText(f.t,f.x-ctx.measureText(f.t).width/2,f.y);ctx.globalAlpha=1});ctx.fillStyle='#f5f7fb';ctx.font='700 16px system-ui';ctx.fillText(alpha?'Alpha Raid Sandbox':'Wild Capture Sandbox',18,26);ctx.font='13px system-ui';ctx.fillStyle='#aab2c5';ctx.fillText(`Active: ${cur().name} — ${cur().def.role}`,18,48);ctx.fillStyle='#f5f7fb';ctx.font='700 14px system-ui';ctx.fillText(`Enemy: ${enemy.name}`,680,26);ctx.fillStyle='#aab2c5';ctx.font='13px system-ui';ctx.fillText(`Damage: ${Math.round(score.dmg)}   ${alpha?'Contribution: '+Math.round(score.dmg):'Captures: '+score.cap}`,680,48);let y=H-118;cur().def.moves.forEach((m,i)=>{let cd=cur().cool[m.id]||0,w=214;ctx.fillStyle='rgba(0,0,0,.45)';ctx.fillRect(18,y,w,22);ctx.fillStyle=m.color;ctx.fillRect(18,y,w*(1-cd/m.cd),22);ctx.fillStyle='#111';ctx.font='700 12px system-ui';ctx.fillText(String(i+1),25,y+15);ctx.fillStyle='#fff';ctx.fillText(`${m.name}${cd>0?' '+cd.toFixed(1):''}`,46,y+15);y+=27})}
let last=performance.now(),acc=0,DT=1/60;function loop(t){acc+=Math.min(.05,(t-last)/1000);last=t;while(acc>=DT){step(DT);acc-=DT}render();requestAnimationFrame(loop)}
reset(false);requestAnimationFrame(loop);
