import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const assetsRoot = path.join(root, "assets");
const jsOut = path.join(root, "src/assets/generatedAssetCatalog.js");
const jsonOut = path.join(root, "data/assets/generated_asset_catalog.json");
const imageExt = new Set([".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg"]);
const dataExt = new Set([".json", ".aseprite", ".tmx", ".tsx"]);

const catalog = {
  schemaVersion: 1,
  generatedBy: "tools/build_asset_catalog.mjs",
  generatedAt: new Date().toISOString(),
  source: "filesystem-scan",
  root: "assets",
  categories: emptyCategories()
};

for (const file of await walk(assetsRoot)) {
  const rel = slash(path.relative(root, file));
  const ext = path.extname(file).toLowerCase();
  if (!imageExt.has(ext) && !dataExt.has(ext)) continue;
  const entry = classify(rel, ext);
  if (!entry) continue;
  catalog.categories[entry.category].push(stripCategory(entry));
}

sortCatalog(catalog);
await mkdir(path.dirname(jsonOut), { recursive: true });
await mkdir(path.dirname(jsOut), { recursive: true });
await writeFile(jsonOut, JSON.stringify(catalog, null, 2) + "\n");
await writeFile(jsOut, `// Generated by tools/build_asset_catalog.mjs. Do not hand edit.\n\nexport const GENERATED_ASSET_CATALOG = ${JSON.stringify(catalog, null, 2)};\n\nexport default GENERATED_ASSET_CATALOG;\n`);
console.log(`Cataloged ${totalCount(catalog)} assets into ${slash(path.relative(root, jsonOut))} and ${slash(path.relative(root, jsOut))}.`);

function emptyCategories() {
  return { bodies: [], hair: [], clothing: [], vfx: [], tilesets: [], stageBackgrounds: [], weapons: [], items: [], fruitIcons: [], props: [], ui: [] };
}

function stripCategory(entry) {
  const { category, ...rest } = entry;
  return rest;
}

async function walk(dir) {
  if (!existsSync(dir)) return [];
  const results = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) results.push(...await walk(full));
    else results.push(full);
  }
  return results;
}

function classify(rel, ext) {
  const lower = rel.toLowerCase();
  const id = idFromPath(rel);
  const base = labelFromPath(rel);
  if (lower.includes("/reference/")) return null;
  if (lower.includes("/characters/")) {
    if (lower.includes("hair") || lower.includes("hairstyle")) return entry("hair", id, base, rel, "hair_part", "hair", ["hair"]);
    if (lower.includes("cloth") || lower.includes("outfit") || lower.includes("armor") || lower.includes("robe")) return entry("clothing", id, base, rel, "clothing_part", "top", ["clothing"]);
    return entry("bodies", id, base, rel, "character_body", "body", ["character", ext.slice(1)], isRuntimeCharacter(rel));
  }
  if (lower.includes("/effects/") || lower.includes("vfx")) return entry("vfx", id, base, rel, "vfx_sheet", null, familyTags(lower));
  if (lower.includes("tileset") || lower.endsWith(".tmx") || lower.endsWith(".tsx")) return entry("tilesets", id, base, rel, "tileset", null, ["stage"]);
  if (lower.includes("background") || lower.includes("backdrop") || lower.includes("stage")) return entry("stageBackgrounds", id, base, rel, "stage_background", null, ["stage"], true, { fit: "cover", alpha: 1 });
  if (lower.includes("weapon") || lower.includes("sword") || lower.includes("blade") || lower.includes("staff") || lower.includes("bow")) return entry("weapons", id, base, rel, "equipment", "weapon", ["weapon", ext.slice(1)]);
  if (lower.includes("fruit") && lower.includes("icon")) return entry("fruitIcons", id, base, rel, "fruit_icon", null, ["fruit", "icon"]);
  if (lower.includes("item") || lower.includes("icon")) return entry("items", id, base, rel, "item_icon", null, ["item", "icon"]);
  if (lower.includes("ui") || lower.includes("hud")) return entry("ui", id, base, rel, "ui_asset", null, ["ui"]);
  return entry("props", id, base, rel, "prop", null, [ext.slice(1)]);
}

function entry(category, id, label, assetPath, kind, slot, tags = [], usable = true, extra = {}) {
  return { id, label, path: assetPath, kind, slot, usable, tags: [...new Set(tags.filter(Boolean))], ...extra };
}

function isRuntimeCharacter(rel) {
  const lower = rel.toLowerCase();
  return lower.includes("prismtek-custom") || lower.includes("tiny-hero");
}

function familyTags(lower) {
  const tags = [];
  for (const family of ["fire", "flame", "ice", "thunder", "lightning", "dark", "earth", "acid", "poison", "holy", "light", "wood", "water", "wind", "hit", "impact"]) {
    if (lower.includes(family)) tags.push(family === "flame" ? "fire" : family === "thunder" ? "lightning" : family);
  }
  return tags.length ? tags : ["effect"];
}

function idFromPath(rel) {
  return rel.replace(/^assets\//, "").replace(/\.[^.]+$/, "").toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
}

function labelFromPath(rel) {
  const name = path.basename(rel, path.extname(rel));
  return name.replace(/[_-]+/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function sortCatalog(c) {
  for (const entries of Object.values(c.categories)) entries.sort((a, b) => a.id.localeCompare(b.id));
}

function totalCount(c) {
  return Object.values(c.categories).reduce((sum, entries) => sum + entries.length, 0);
}

function slash(value) {
  return value.split(path.sep).join("/");
}
