import { readdir, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const assetsRoot = path.join(root, "assets");
const jsOut = path.join(root, "src/assets/generatedAssetCatalog.js");
const jsonOut = path.join(root, "data/assets/generated_asset_catalog.json");
const imageExt = new Set([".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg"]);
const dataExt = new Set([".json", ".aseprite", ".tmx", ".tsx"]);
const approvedRuntimePaths = new Set([
  "assets/characters/prismtek-custom/male-basic.svg",
  "assets/characters/prismtek-custom/female-basic.svg",
  "assets/characters/tiny-hero/pink/idle_4.png",
  "assets/characters/tiny-hero/owlet/idle_4.png",
  "assets/characters/tiny-hero/dude/idle_4.png",
  "assets/effects/elemental-vfx/firebolt.png",
  "assets/effects/elemental-vfx/ice-hit.png",
  "assets/effects/elemental-vfx/thunder-beam.png",
  "assets/effects/elemental-vfx/dark-column.png",
  "assets/effects/elemental-vfx/earth-impact.png",
  "assets/effects/elemental-vfx/acid-splash.png",
  "assets/effects/elemental-vfx/holy-column.png",
  "assets/effects/elemental-vfx/hit-spark.png",
  "assets/stages/four-seasons/four-seasons-tileset.png"
]);

const catalog = {
  schemaVersion: 2,
  generatedBy: "tools/build_asset_catalog.mjs",
  generatedAt: new Date().toISOString(),
  source: "filesystem-scan-curated",
  root: "assets",
  policy: {
    defaultStatus: "discovered",
    runtimeRule: "Only assets with status=approved and runtimeReady=true are surfaced in game selectors.",
    reason: "The repository can contain multiple art styles, animation formats, test assets, source files, and game types. Discovery is not approval."
  },
  categories: emptyCategories()
};

for (const file of await walk(assetsRoot)) {
  const rel = slash(path.relative(root, file));
  const ext = path.extname(file).toLowerCase();
  if (!imageExt.has(ext) && !dataExt.has(ext)) continue;
  const entry = classify(rel, ext);
  if (!entry) continue;
  catalog.categories[entry.category].push(stripCategory(entry));
}

sortCatalog(catalog);
await mkdir(path.dirname(jsonOut), { recursive: true });
await mkdir(path.dirname(jsOut), { recursive: true });
await writeFile(jsonOut, JSON.stringify(catalog, null, 2) + "\n");
await writeFile(jsOut, `// Generated by tools/build_asset_catalog.mjs. Do not hand edit.\n\nexport const GENERATED_ASSET_CATALOG = ${JSON.stringify(catalog, null, 2)};\n\nexport default GENERATED_ASSET_CATALOG;\n`);
console.log(`Cataloged ${totalCount(catalog)} discovered assets; ${approvedCount(catalog)} approved runtime assets.`);

function emptyCategories() {
  return { bodies: [], hair: [], clothing: [], vfx: [], tilesets: [], stageBackgrounds: [], weapons: [], items: [], fruitIcons: [], props: [], ui: [] };
}

function stripCategory(entry) {
  const { category, ...rest } = entry;
  return rest;
}

async function walk(dir) {
  if (!existsSync(dir)) return [];
  const results = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) results.push(...await walk(full));
    else results.push(full);
  }
  return results;
}

function classify(rel, ext) {
  const lower = rel.toLowerCase();
  const id = idFromPath(rel);
  const base = labelFromPath(rel);
  if (lower.includes("/reference/")) return null;
  if (lower.includes("/characters/")) {
    if (lower.includes("hair") || lower.includes("hairstyle")) return entry("hair", id, base, rel, "hair_part", "hair", ["hair", ext.slice(1)]);
    if (lower.includes("cloth") || lower.includes("outfit") || lower.includes("armor") || lower.includes("robe")) return entry("clothing", id, base, rel, "clothing_part", "top", ["clothing", ext.slice(1)]);
    return entry("bodies", id, base, rel, "character_body", "body", ["character", ext.slice(1)]);
  }
  if (lower.includes("/effects/") || lower.includes("vfx")) return entry("vfx", id, base, rel, "vfx_sheet", null, familyTags(lower));
  if (lower.includes("tileset") || lower.endsWith(".tmx") || lower.endsWith(".tsx")) return entry("tilesets", id, base, rel, "tileset", null, ["stage", ext.slice(1)]);
  if (lower.includes("background") || lower.includes("backdrop") || lower.includes("stage")) return entry("stageBackgrounds", id, base, rel, "stage_background", null, ["stage", ext.slice(1)], { fit: "cover", alpha: 1 });
  if (lower.includes("weapon") || lower.includes("sword") || lower.includes("blade") || lower.includes("staff") || lower.includes("bow")) return entry("weapons", id, base, rel, "equipment", "weapon", ["weapon", ext.slice(1)]);
  if (lower.includes("fruit") && lower.includes("icon")) return entry("fruitIcons", id, base, rel, "fruit_icon", null, ["fruit", "icon", ext.slice(1)]);
  if (lower.includes("item") || lower.includes("icon")) return entry("items", id, base, rel, "item_icon", null, ["item", "icon", ext.slice(1)]);
  if (lower.includes("ui") || lower.includes("hud")) return entry("ui", id, base, rel, "ui_asset", null, ["ui", ext.slice(1)]);
  return entry("props", id, base, rel, "prop", null, [ext.slice(1)]);
}

function entry(category, id, label, assetPath, kind, slot, tags = [], extra = {}) {
  const approved = approvedRuntimePaths.has(assetPath);
  return {
    id,
    label,
    path: assetPath,
    kind,
    slot,
    status: approved ? "approved" : "discovered",
    runtimeReady: approved,
    usable: approved,
    styleFamily: approved ? "pixel-fruit-arena" : inferStyleFamily(assetPath),
    compatibility: approved ? ["pixel-fruit-arena-runtime"] : [],
    notes: approved ? "Curated for the current Pixel Fruit Arena runtime." : "Discovered only. Review art style, frame geometry, licensing, animation type, and runtime compatibility before enabling.",
    tags: [...new Set(tags.filter(Boolean))],
    ...extra
  };
}

function inferStyleFamily(assetPath) {
  const lower = assetPath.toLowerCase();
  if (lower.includes("tiny-hero") || lower.includes("prismtek-custom") || lower.includes("elemental-vfx") || lower.includes("four-seasons")) return "pixel-fruit-arena-candidate";
  if (lower.includes("aseprite")) return "source-art";
  if (lower.includes("tiles") || lower.endsWith(".tmx") || lower.endsWith(".tsx")) return "tilemap-candidate";
  return "uncurated";
}

function familyTags(lower) {
  const tags = [];
  for (const family of ["fire", "flame", "ice", "thunder", "lightning", "dark", "earth", "acid", "poison", "holy", "light", "wood", "water", "wind", "hit", "impact"]) {
    if (lower.includes(family)) tags.push(family === "flame" ? "fire" : family === "thunder" ? "lightning" : family);
  }
  return tags.length ? tags : ["effect"];
}

function idFromPath(rel) {
  return rel.replace(/^assets\//, "").replace(/\.[^.]+$/, "").toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
}

function labelFromPath(rel) {
  const name = path.basename(rel, path.extname(rel));
  return name.replace(/[_-]+/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function sortCatalog(c) {
  for (const entries of Object.values(c.categories)) entries.sort((a, b) => a.id.localeCompare(b.id));
}

function totalCount(c) {
  return Object.values(c.categories).reduce((sum, entries) => sum + entries.length, 0);
}

function approvedCount(c) {
  return Object.values(c.categories).reduce((sum, entries) => sum + entries.filter((entry) => entry.status === "approved" && entry.runtimeReady === true).length, 0);
}

function slash(value) {
  return value.split(path.sep).join("/");
}
