import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SOURCE_URL = "https://shipoffools.fandom.com/wiki/Devil_Fruit_Encyclopedia";
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "src/fruits/generatedShipOfFoolsFruits.js");
const DATA_OUT = path.join(ROOT, "data/fruits/shipoffools-fruits.generated.json");
const KIND_BY_TYPE = {
  logia: ["projectile", "field", "dash"],
  zoan: ["melee", "dash", "uppercut"],
  "ancient zoan": ["melee", "dash", "heavy"],
  "mythical zoan": ["melee", "burst", "uppercut"],
  paramecia: ["projectile", "field", "heavy"]
};
const COLORS = ["#ff6b35", "#8fd8ff", "#ffe45e", "#7c5cff", "#ff8fab", "#9be564", "#f4a261", "#2dd4bf", "#c084fc", "#f97316"];

const html = await fetchText(SOURCE_URL);
const rows = parseRows(html);
if (rows.length < 25) throw new Error(`Only parsed ${rows.length} fruits. Page structure may have changed.`);
const fruits = Object.fromEntries(rows.map((row, index) => [row.id, buildRuntimeFruit(row, index)]));

await writeFile(OUT, `// Generated by tools/import_shipoffools_fruits.mjs.\n// Source: ${SOURCE_URL}\n// The source page says the encyclopedia belongs to the Ship of Fools wiki and is not up to date.\n// Review source permissions before public redistribution.\nexport const SHIP_OF_FOOLS_FRUITS = ${JSON.stringify(fruits, null, 2)};\n`);
await writeFile(DATA_OUT, `${JSON.stringify(Object.values(fruits).map(({ id, name, encyclopediaType, abilities, awakening, source }) => ({ id, name, encyclopediaType, abilities: abilities.map((ability) => ability.name), awakening, source })), null, 2)}\n`);
console.log(`Imported ${rows.length} Ship of Fools encyclopedia fruits into Pixel Fruit Arena.`);

async function fetchText(url) {
  const response = await fetch(url, { headers: { "user-agent": "PixelFruitArenaAssetImporter/1.0" } });
  if (!response.ok) throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
  return response.text();
}

function parseRows(html) {
  const text = html
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&#039;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/\s+/g, " ");
  const matches = [...text.matchAll(/([A-ZĀŌŪĒĪa-zāōūēī'\- ]+? no Mi(?:, Model: [A-ZĀŌŪĒĪa-zāōūēī'\- ]+)?|[A-Z][A-Za-z'\-]+-[A-Z][A-Za-z'\-]+ No Mi)\s+([A-Z][A-Za-z'\- ]+ Fruit(?:, Model: [A-Z][A-Za-z'\- ]+)?)\s+(Mythical Zoan|Ancient Zoan|Zoan|Logia|Paramecia|paramecia)\s+(.{10,220}?)(?=\s+(?:N\/A|[A-ZĀŌŪĒĪa-zāōūēī'\-]+\s+[A-ZĀŌŪĒĪa-zāōūēī'\-]+|User:|claimed by|[A-ZĀŌŪĒĪ][a-zāōūēī]+ [A-ZĀŌŪĒĪ]|[A-Z]\s|[A-ZĀŌŪĒĪa-zāōūēī'\- ]+? no Mi))/g)];
  const seen = new Set();
  return matches.map((match) => {
    const englishName = cleanName(match[2]);
    const baseId = slugify(englishName);
    return {
      id: `sof_${baseId}`,
      originalName: cleanName(match[1]),
      englishName,
      type: titleCase(match[3]),
      powerHint: cleanPower(match[4])
    };
  }).filter((row) => {
    if (!row.id || !row.englishName.endsWith("Fruit") && !row.englishName.includes("Fruit,")) return false;
    if (seen.has(row.id)) return false;
    seen.add(row.id);
    return true;
  });
}

function buildRuntimeFruit(row, index) {
  const typeKey = row.type.toLowerCase();
  const kinds = KIND_BY_TYPE[typeKey] || KIND_BY_TYPE.paramecia;
  const base = 8 + (index % 5);
  const icon = row.englishName.replace(/[^A-Za-z]/g, "").charAt(0).toUpperCase() || "?";
  const theme = row.englishName.replace(/ Fruit(?:, Model: .*)?$/, "");
  return {
    id: row.id,
    name: row.englishName,
    color: COLORS[index % COLORS.length],
    icon,
    category: "Ship of Fools Encyclopedia",
    encyclopediaType: row.type,
    source: { url: SOURCE_URL, originalName: row.originalName, powerHint: row.powerHint, licenseReviewRequired: true },
    awakening: `${theme} Awakening`,
    abilities: [
      { id: `${row.id}_shot`, name: `${theme} Shot`, kind: kinds[0], damage: base, knockback: 300 + (index % 6) * 35, cooldown: 0.55, speed: 460 + (index % 5) * 70 },
      { id: `${row.id}_surge`, name: `${theme} Surge`, kind: kinds[1], damage: base + 2, knockback: 360 + (index % 7) * 30, cooldown: 0.95, slow: typeKey.includes("logia") ? 0.55 : undefined },
      { id: `${row.id}_breaker`, name: `${theme} Breaker`, kind: kinds[2], damage: base + 5, knockback: 520 + (index % 5) * 45, cooldown: 1.25, range: 88 }
    ].map(stripUndefined)
  };
}

function stripUndefined(value) { return Object.fromEntries(Object.entries(value).filter(([, entry]) => entry !== undefined)); }
function cleanName(value) { return value.replace(/\s+/g, " ").trim(); }
function cleanPower(value) { return cleanName(value).replace(/\s+N\/A\s+.*$/, "").slice(0, 180); }
function slugify(value) { return value.toLowerCase().replace(/fruit.*/g, "fruit").replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, ""); }
function titleCase(value) { return value.toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase()); }
